//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class EditorSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static EditorSetting defaultInstance = ((EditorSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EditorSetting())));
        
        public static EditorSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList D {
            get {
                return ((global::System.Collections.ArrayList)(this["D"]));
            }
            set {
                this["D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectionPage {
            get {
                return ((int)(this["SelectionPage"]));
            }
            set {
                this["SelectionPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedNode {
            get {
                return ((string)(this["SelectedNode"]));
            }
            set {
                this["SelectedNode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList IsExPand {
            get {
                return ((global::System.Collections.ArrayList)(this["IsExPand"]));
            }
            set {
                this["IsExPand"] = value;
            }
        }
    }
}
